name: Update Defense Pulse Feed

on:
  schedule:
    - cron: '0 */4 * * *' # Toutes les 4 heures
  workflow_dispatch: # Permet de lancer manuellement depuis l'onglet Actions

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Important pour permettre le push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install feedparser
          
      - name: Run update script
        run: python ./update_feed.py
        

      - name: Commit and push if changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add news.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update news feed: $(date +'%Y-%m-%d %H:%M')" && git push)
